### ISSUE TITLE
some question with cppsignalrclient

### ISSUE THREAD

**Issue by shanghaimoon888** [SignalR/SignalR-Client-Cpp#141]
when i run the sample client to connect to the signalr server, it shows:
 exception when starting or stopping connection: websockets not supported on the
server and there is no fallback transport

what's the problem? My system is windows 7  professional.

**Comment by shanghaimoon888** [comment]
o, at last i found the problem, at this time the cppclient is just use websocket. So the server should be win2012 and iis80. Otherwise the websocket will not work.

**Comment by moozzyk** [comment]
Yes at the moment C++ client supports only websockets transport. #62
