### ISSUE TITLE
Mac/cross platform support with Qt

### ISSUE THREAD

**Issue by Aeroxander** [SignalR/SignalR-Client-Cpp#144]
I want to be able to just write the client once in C++, will Mac be ever supported or do I just have to write in Objective-C?

**Comment by Aeroxander** [comment]
I'd love to figure it out to run it on mac, but I've got no mac to test it on 😛

**Comment by moozzyk** [comment]
I actually got it building but had some issues linking with boost - need to get back to it. (btw. I actually think I saw an Objective-C client 'on the netz').

**Comment by Aeroxander** [comment]
Ah, I'd be wonderful if you could make it work in a 1-3 months, I don't want to pressure you or anything like that though haha. 
_If I'd have C++ working cross-platform with SignalR Core on Linux I'd have the ultimate cross-platform application 🙊 Good (tech) times!_

**Comment by Aeroxander** [comment]
Just wanted to say that I right now use an WebView in Qt and connect it with the C++ code over QWebChannel (local websocket server).  It works quite well already!
