### ISSUE TITLE
SignalR Sample is not getting build with VS2013 toolset.

### ISSUE THREAD

**Issue by taruntomar** [SignalR/SignalR-Client-Cpp#146]
hi, 

I am getting the following error on invoking some hub method from proxy, while building it with VS2013.

_> error c 1001: An internal error has occurred in the compiler._ 
proxy.invoke<void>(U("HitCounter")).get();

Are there is some problem with toolset compatibility not with the configuration, as it is working fine with Visual Studio 2015 toolset?

**Comment by moozzyk** [comment]
There is a comment on this in the sample: https://github.com/aspnet/SignalR-Client-Cpp/blob/dev/samples/HubConnectionSample/HubConnectionSample.cpp#L13

Hope this helps.
