### ISSUE TITLE
Update nuget package to use cpprest 2.9.1 (https://www.nuget.org/packages/cpprestsdk/2.9.1.1)

### ISSUE THREAD

**Issue by remusrg** [SignalR/SignalR-Client-Cpp#147]
Do you mind updating your nuget package / library to use cpprest 2.9.1? Lots of good fixes since 2.7 plus I have a related project that is already using 2.9.1 in the same solution and I end up loading both libraries at runtime.

Thank you!

**Comment by moozzyk** [comment]
Need to see what changed

**Comment by moozzyk** [comment]
This was merged in cb91fe8991879b8ef4cc1109e9556c7e9a838605. Note samples were not updated since they use the package from NuGet.

**Comment by remusrg** [comment]
Publish updated package on nuget.org?

**Comment by moozzyk** [comment]
Not for now. You can get the latest package built by the CI from this feed: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json (https://dotnet.myget.org/gallery/aspnetcore-ci-dev)

**Comment by remusrg** [comment]
Has this progressed to release or nuget.org at this point or should we still use the feed above?

**Comment by moozzyk** [comment]
It has not been released to NuGet yet. Sorry.
