### ISSUE TITLE
LNK2019 error running Signalr on Visual Studio 2015 - Windows XP (v140_xp) Platform Toolset

### ISSUE THREAD

**Issue by OenSG** [SignalR/SignalR-Client-Cpp#156]
I'm trying to set up a persistent connection with a computer using XP and I'm consistently getting the error,

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: class Concurrency::task<void> __cdecl signalr::connection::start(void)" (__imp_?start@connection@signalr@@QAA?AV?$task@X@Concurrency@@XZ) referenced in function _main	PersistentConnectionSample

,while trying to run the sample code. Is it possible to run this on Windows XP? If so, how would I got about it?

Thanks a bunch!

**Comment by moozzyk** [comment]
SignalR client is compiled only with v120 and v140 toolsets. My understanding is that to try to make it work on Windows XP it would have to be compiled using v120_xp toolset (http://stackoverflow.com/questions/32580151/what-is-the-difference-between-v120-xp-and-v120-on-vs-2013). Given that Windows XP is no longer supported there are no plans to do that. You can however try compiling it yourself. You would have to pass 'PlatfromToolset' as the parameter to msbuild (i.e. clone and using the dev console run the following command from root repo `msbuild build\build.msbuild /p:PlatformToolset=v120_xp /p:Configuration=Release`). Note that you have to have the v120_xp toolset installed. Note also that there are no guarantees it will compile or work. As I said Windows XP is no longer supported.
