### ISSUE TITLE
ignoring certificate validation

### ISSUE THREAD

**Issue by meirb** [SignalR/SignalR-Client-Cpp#161]
We are an ISV and we are deploying a self sign certificate in order to use SSL to encrypt the transport (not for mutual authentication) 
We would like to have the option to ignore certificate validation on the client (like in http_clinet, http_client_config.set_validate_certificates)
is this available somehow in the current API, if not can this be added?

**Comment by moozzyk** [comment]
You can now set the client config https://github.com/aspnet/SignalR-Client-Cpp/blob/2021090834777493837c9cc70a948b186fa617c7/include/signalrclient/signalr_client_config.h#L23
This version is not on NuGet yet but until it is published you can use a nightly build from this feed: https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json (here is the gallery: https://dotnet.myget.org/gallery/aspnetcore-ci-dev)
