### ISSUE TITLE
Nightly builds not available

### ISSUE THREAD

**Issue by matelich** [SignalR/SignalR-Client-Cpp#164]
https://dotnet.myget.org/gallery/aspnetcore-dev shows the last build from 6 months ago.

**Comment by matelich** [comment]
Maybe that's off master, not dev.

**Comment by moozzyk** [comment]
This is the correct feed: https://dotnet.myget.org/gallery/aspnetcore-ci-dev. "Nightly" is an exaggeration - the build is triggered if there are new commits.

**Comment by moozzyk** [comment]
Updated README in fd6ce05
