### ISSUE TITLE
Usage of SignalR with c++ in Ubuntu

### ISSUE THREAD

**Issue by mumincelal** [SignalR/SignalR-Client-Cpp#169]
SignalR-Client-Cpp project was downloaded and imported some files to another project on Linux. CppRestSdk was downloaded and installed.

How to use SignalR in Linux? How to do Hub connection with it in Linux?

**Comment by moozzyk** [comment]
See samples e.g.: https://github.com/aspnet/SignalR-Client-Cpp/tree/dev/samples/HubConnectionSample
