### ISSUE TITLE
Move this repo to SignalR organization

### ISSUE THREAD

**Issue by muratg** [SignalR/SignalR-Client-Cpp#170]
This repo contains the C++ client code for SignalR 2.x (classic)

We'd like to move this to SignalR organization.  @Eilon, is this OK?

cc @moozzyk @davidfowl @BrennanConroy

**Comment by Eilon** [comment]
Yeah sure. Is it good to go? Is there any back-end CI stuff we need to change? Does Coherence-Signed or MicroBuild-Signed or TeamCity need to be updated in any way?

**Comment by moozzyk** [comment]
@Eilon - MicroBuild-Signed signs the output but it is using a share as a source. I will fix CI when/if we need to build it again - because we don't build this repo often typically you need to fix CI anyways...

**Comment by Eilon** [comment]
Ok so I'll move the repo in like an hour unless I hear an objection to it.

**Comment by Eilon** [comment]
DONE

**Comment by muratg** [comment]
Thanks!
