### ISSUE TITLE
Is this SignalR 1 or SignalR 2?

### ISSUE THREAD

**Issue by AndrewRogers1994** [SignalR/SignalR-Client-Cpp#172]
I was wondering what version of SignalR this currently supports, I'm assuming probably SignalR 1 but I just want to be sure.

**Comment by moozzyk** [comment]
What do you refer to a 'SignalR1' and 'SignalR2'? 
This client is for SignalR 2.x (so, **not** the ASP.Net Core version of SignalR developed [here](http://github.com/aspnet/SignalR)).
