### ISSUE TITLE
Getting started...

### ISSUE THREAD

**Issue by ramiz4** [SignalR/SignalR-Client-Cpp#44]
Hi,

im missing a getting started in the readme file. 
Im trying to build a c++ client which connect to signalr in a mvc5 web application.

Thank you

**Comment by moozzyk** [comment]
@ramiz4 - if you now clone/fetch and run build.cmd from VS2013 command prompt in the repo root it will build and run the tests. The binaries will be in bin\[Debug|Release]\[Win32|x64]\v120\[lib|dll].
